name: Deploy

on:
  workflow_dispatch:
      branch:
        description: The branch to deploy
        required: true
        default: main
  push:
    branches: [main]
jobs:
  setup:
    name: Setup workflow variables
    runs-on: ubuntu-latest
    steps:
    - name: should be redacted
      env: # Or as an environment variable
        secret: ${{ secrets.FIND_ME }}
      run: echo $secret
    - name: to file
      env: # Or as an environment variable
        secret: ${{ secrets.FIND_ME }}
      run: echo $secret > test.txt
    - name: cat test
      run: cat test.txt
    - name: all in one
      env: # Or as an environment variable
        secret: ${{ secrets.FIND_ME }}
      run: echo $secret > test.txt && cat test.txt
