name: Deploy

on:
  workflow_dispatch:
      branch:
        description: The branch to deploy
        required: true
        default: main
  push:
    branches: [main]
jobs:
  setup:
    name: Setup workflow variables
    runs-on: ubuntu-latest
    steps:
    - name: Hello world action
      env: # Or as an environment variable
        secret: ${{ secrets.FIND_ME }}
      run: echo $secret
    - name: print secret
      run: echo $secret
      with:
        secret: ${{ secrets[needs.setup.outputs.secret] }}
    - name: print secret again
      run: echo ${{  needs.setup.outputs.secret  }}
      with:
        secret: ${{ secrets[needs.setup.outputs.secret] }}
    - name: print secret to file
      run: echo ${{  needs.setup.outputs.secret  }} > test.txt && cat test.txt
      with:
        secret: ${{ secrets[needs.setup.outputs.secret] }}